import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import Script from "next/script";
import { getDirection } from "@/lib/i18n/config";
import { parseLocaleFromCookie, parseLocaleFromHeader } from "@/lib/i18n/server";
import CookieBanner from "@/components/legal/CookieBanner";
import "./globals.css";

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://tenu.world";
const SITE_NAME = "Tenu.World";
const DEFAULT_TITLE = "Tenu — Your Rights. Your Language. Your Deposit.";
const DEFAULT_DESCRIPTION =
  "AI-powered tenant rights companion for international renters in France and the UK. Scan your deposit risk from photos in under two minutes. Generate ready-to-send dispute letters.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: DEFAULT_TITLE,
    template: "%s — Tenu.World",
  },
  description: DEFAULT_DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  keywords: [
    "tenant rights",
    "rental deposit",
    "deposit dispute",
    "depot de garantie",
    "caution locative",
    "tenancy deposit",
    "TDS",
    "DPS",
    "MyDeposits",
    "France",
    "United Kingdom",
    "caisse des depots",
    "AI tenant tool",
    "international renters",
    "students renting",
  ],
  authors: [{ name: "Global Apex.Net", url: SITE_URL }],
  creator: "Global Apex.Net SAS",
  publisher: "Global Apex.Net SAS",
  category: "legaltech",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: "/",
    languages: {
      "en": "/",
      "fr-FR": "/",
      "x-default": "/",
    },
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    alternateLocale: ["fr_FR"],
    url: SITE_URL,
    siteName: SITE_NAME,
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Tenu — Your rights, your language, your deposit",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // Icons auto-generated by src/app/icon.tsx and src/app/apple-icon.tsx.
  manifest: "/manifest.webmanifest",
  verification: {
    // Populate once Google Search Console and Bing Webmaster Tools are set up.
    // google: "",
    // other: { "msvalidate.01": "" },
  },
};

// JSON-LD: Organization schema. Feeds knowledge panels and AEO surfaces.
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${SITE_URL}#organization`,
  name: "Global Apex.Net",
  legalName: "Global Apex.Net SAS",
  alternateName: "Tenu.World",
  url: SITE_URL,
  // Logo omitted until a 512x512 square brand asset is produced.
  description: DEFAULT_DESCRIPTION,
  foundingDate: "2024",
  address: {
    "@type": "PostalAddress",
    streetAddress: "4 Boulevard du Chateau",
    postalCode: "78280",
    addressLocality: "Guyancourt",
    addressRegion: "Ile-de-France",
    addressCountry: "FR",
  },
  contactPoint: [
    {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: "support@tenu.world",
      availableLanguage: ["English", "French"],
    },
    {
      "@type": "ContactPoint",
      contactType: "data protection",
      email: "dpo@tenu.world",
      availableLanguage: ["English", "French"],
    },
  ],
  identifier: [
    { "@type": "PropertyValue", propertyID: "SIREN", value: "941666067" },
    { "@type": "PropertyValue", propertyID: "RCS", value: "Versailles 941 666 067" },
  ],
  sameAs: ["https://github.com/malikmubashir/tenu-world"],
};

// JSON-LD: WebSite schema. Enables sitelinks search box if we wire search later.
const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}#website`,
  url: SITE_URL,
  name: SITE_NAME,
  description: DEFAULT_DESCRIPTION,
  publisher: { "@id": `${SITE_URL}#organization` },
  inLanguage: ["en", "fr"],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const headerStore = await headers();

  const cookieLocale = cookieStore.get("locale")?.value;
  const locale = cookieLocale
    ? parseLocaleFromCookie(cookieLocale)
    : parseLocaleFromHeader(headerStore.get("accept-language") ?? undefined);

  const dir = getDirection(locale);

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <head>
        <Script
          id="ld-organization"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <Script
          id="ld-website"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </head>
      <body className="min-h-screen bg-tenu-cream text-tenu-slate antialiased">
        {children}
        <CookieBanner locale={locale === "fr" ? "fr" : "en"} />
      </body>
    </html>
  );
}
