// /features/dispute — "A letter that defends itself" / "Une lettre qui se
// défend toute seule". Dispute letter add-on: Sonnet-generated CDC-format
// letter in French, paired with a plain explanation in the tenant's language.
import { cookies, headers } from "next/headers";
import Link from "next/link";
import { parseLocaleFromCookie, parseLocaleFromHeader } from "@/lib/i18n/server";

type Copy = {
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  lede: string;
  containsHeading: string;
  containsItems: { title: string; body: string }[];
  craftHeading: string;
  craftBody: string;
  useHeading: string;
  useSteps: string[];
  priceHeading: string;
  priceBody: string;
  closingHeading: string;
  closingBody: string;
  cta: string;
  disclaimer: string;
  home: string;
  pricing: string;
};

const EN: Copy = {
  metaTitle: "A letter that defends itself — Tenu.World dispute add-on",
  metaDescription:
    "A formal dispute letter in French, CDC format, grounded in Loi 89-462 and the wear-and-tear scale. Delivered with a plain explanation in your own language.",
  eyebrow: "Feature · Dispute letter",
  title: "A letter that defends itself",
  lede:
    "A formal letter in French, structured like a conciliation commission brief, addressed to your landlord. You sign it. You send it. Twenty euros, add-on to the risk scan.",
  containsHeading: "What the letter contains",
  containsItems: [
    {
      title: "Formal opening and parties",
      body: "Full identification of tenant and landlord, date, lease reference, address of the dwelling. Registered letter format with acknowledgement of receipt.",
    },
    {
      title: "Statement of facts",
      body: "Dates of entry and exit, date of key return, date the deposit should have been returned under article 22 of Loi 89-462.",
    },
    {
      title: "Reasoned challenge of each deduction",
      body: "Line by line, each deduction claimed by the landlord is answered. Normal wear is pushed back with a reference to the arrêté du 19 mars 2020. Imputable damage is answered with the residual value, not the replacement cost. Unsupported deductions are challenged on burden of proof.",
    },
    {
      title: "Quantified demand",
      body: "The exact amount the tenant is owed, broken down: deposit balance + interest at 10 % of monthly rent per month of delay (article 22 of Loi 89-462).",
    },
    {
      title: "Deadline and legal recourse",
      body: "Eight-day deadline to respond. Statement that failure to pay will be referred to the Commission départementale de conciliation and, if necessary, to the juge des contentieux de la protection.",
    },
    {
      title: "Annexes",
      body: "The evidence bundle (photos + hashes + timestamps), the AI risk scan, and any prior correspondence. Referenced in the body of the letter by annex number.",
    },
  ],
  craftHeading: "How the letter is written",
  craftBody:
    "The letter is generated by Claude Sonnet, not by a template. Sonnet receives your risk scan output and the entry/exit photos, and drafts a letter in the register of a French legal practitioner: formal address, precise statute references, no padding, no threats, no consumer-advocacy tone. The output is validated against a zod schema before delivery, with the total line items summing to within one euro of the stated demand.",
  useHeading: "How to use it",
  useSteps: [
    "Review the French letter and the explanation in your language. Make sure the facts match your situation.",
    "Print or export to PDF. Sign the printed copy.",
    "Send by registered letter with acknowledgement of receipt (recommandé avec accusé de réception). That gives it legal weight.",
    "Keep the post-office receipt. It is the proof you sent the letter on a specific date.",
    "If no reply within eight days, file with the Commission départementale de conciliation. The letter becomes your opening brief.",
  ],
  priceHeading: "Price",
  priceBody:
    "€20, paid once the risk scan report shows a non-zero challenge. You do not pay for a letter when the scan tells you the landlord's deduction is defensible.",
  closingHeading: "A letter you sign, not a letter you write.",
  closingBody:
    "The dispute add-on is available after the scan completes and only if the scan finds something to challenge.",
  cta: "Run the scan first",
  disclaimer:
    "The dispute letter is a template produced from your scan. Tenu does not represent you. For representation before a court, retain an avocat.",
  home: "Home",
  pricing: "Pricing",
};

const FR: Copy = {
  metaTitle: "Une lettre qui se défend toute seule — Option contestation Tenu.World",
  metaDescription:
    "Une lettre formelle en français, au format commission de conciliation, fondée sur la loi du 6 juillet 1989 et l'arrêté du 19 mars 2020. Livrée avec une explication claire dans votre langue.",
  eyebrow: "Fonctionnalité · Lettre de contestation",
  title: "Une lettre qui se défend toute seule",
  lede:
    "Une lettre formelle en français, structurée comme un mémoire de conciliation, adressée à votre bailleur. Vous la signez. Vous l'envoyez. 20 €, en complément de l'analyse.",
  containsHeading: "Ce que contient la lettre",
  containsItems: [
    {
      title: "Ouverture formelle et identification des parties",
      body: "Identification complète du locataire et du bailleur, date, référence du bail, adresse du logement. Format courrier recommandé avec accusé de réception.",
    },
    {
      title: "Exposé des faits",
      body: "Dates d'entrée et de sortie, date de restitution des clés, date à laquelle le dépôt aurait dû être rendu en application de l'article 22 de la loi du 6 juillet 1989.",
    },
    {
      title: "Contestation motivée, retenue par retenue",
      body: "Ligne par ligne, chaque retenue avancée par le bailleur est contestée. L'usure normale est rejetée au visa de l'arrêté du 19 mars 2020. Les dégradations imputables sont chiffrées à leur valeur résiduelle, non au coût d'un remplacement à neuf. Les retenues non étayées sont contestées sur la charge de la preuve.",
    },
    {
      title: "Demande chiffrée",
      body: "Montant exact dû au locataire, ventilé : solde du dépôt + intérêts de 10 % du loyer mensuel par mois de retard (article 22 de la loi du 6 juillet 1989).",
    },
    {
      title: "Délai et voies de recours",
      body: "Délai de huit jours pour répondre. Mention que, à défaut, la saisine de la commission départementale de conciliation puis, le cas échéant, du juge des contentieux de la protection, sera engagée.",
    },
    {
      title: "Annexes",
      body: "Le dossier de preuves (photos + empreintes + horodatages), le rapport d'analyse IA, toute correspondance antérieure. Chaque pièce est appelée par numéro d'annexe dans le corps de la lettre.",
    },
  ],
  craftHeading: "Comment la lettre est rédigée",
  craftBody:
    "La lettre est générée par Claude Sonnet, non par un simple modèle. Sonnet reçoit le rapport d'analyse et les photos d'entrée et de sortie, puis rédige dans le registre d'un praticien du droit français : adresses formelles, références de textes précises, sans verbiage, sans intimidation, sans ton militant. La sortie est validée par un schéma zod avant livraison, et le total des lignes chiffrées converge à un euro près sur la demande formulée.",
  useHeading: "Comment l'utiliser",
  useSteps: [
    "Relisez la lettre française et l'explication dans votre langue. Vérifiez que les faits correspondent à votre situation.",
    "Imprimez ou exportez en PDF. Signez l'exemplaire imprimé.",
    "Envoyez en lettre recommandée avec accusé de réception. C'est ce qui donne date certaine à votre courrier.",
    "Conservez le récépissé postal. Il constitue la preuve que vous avez envoyé la lettre à telle date.",
    "Sans réponse sous huit jours, saisissez la commission départementale de conciliation. La lettre devient votre mémoire d'ouverture.",
  ],
  priceHeading: "Prix",
  priceBody:
    "20 €, réglés après que l'analyse a conclu à une retenue contestable. Vous ne payez pas pour une lettre lorsque l'analyse indique que la retenue du bailleur est défendable.",
  closingHeading: "Une lettre que vous signez, pas une lettre que vous rédigez.",
  closingBody:
    "L'option contestation est disponible à l'issue de l'analyse et uniquement si celle-ci identifie un point à contester.",
  cta: "Commencer par l'analyse",
  disclaimer:
    "La lettre de contestation est un modèle établi à partir de votre analyse. Tenu ne vous représente pas. Pour une représentation devant une juridiction, mandatez un avocat.",
  home: "Accueil",
  pricing: "Tarifs",
};

async function resolveCopy(): Promise<Copy> {
  const cookieStore = await cookies();
  const headerStore = await headers();
  const cookieLocale = cookieStore.get("locale")?.value;
  const locale = cookieLocale
    ? parseLocaleFromCookie(cookieLocale)
    : parseLocaleFromHeader(headerStore.get("accept-language") ?? undefined);
  return locale === "fr" ? FR : EN;
}

export async function generateMetadata() {
  const c = await resolveCopy();
  return { title: c.metaTitle, description: c.metaDescription };
}

export default async function DisputeFeature() {
  const c = await resolveCopy();
  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex items-center justify-between px-6 py-4 md:px-12">
        <Link href="/" className="text-2xl font-bold text-tenu-forest">tenu</Link>
        <nav className="flex items-center gap-4 text-sm">
          <Link href="/" className="text-tenu-slate hover:text-tenu-forest">{c.home}</Link>
          <Link href="/pricing" className="text-tenu-slate hover:text-tenu-forest">{c.pricing}</Link>
        </nav>
      </header>

      <main className="flex flex-1 flex-col">
        <section className="t-section-canvas px-6 text-center">
          <span className="t-label mb-5 inline-block text-tenu-accent">{c.eyebrow}</span>
          <h1 className="t-display mx-auto max-w-4xl">{c.title}</h1>
          <p className="t-body-muted mx-auto mt-6 max-w-2xl">{c.lede}</p>
        </section>

        <section className="t-section-band px-6 md:px-12">
          <div className="t-content max-w-3xl">
            <h2 className="t-section-heading mb-10">{c.containsHeading}</h2>
            <div className="grid gap-6 md:grid-cols-2">
              {c.containsItems.map((it) => (
                <div key={it.title} className="t-card">
                  <h3 className="t-h3 mb-2">{it.title}</h3>
                  <p className="t-small-muted">{it.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="t-section-canvas px-6 md:px-12">
          <div className="t-content max-w-3xl">
            <h2 className="t-section-heading mb-4">{c.craftHeading}</h2>
            <p className="t-body">{c.craftBody}</p>
          </div>
        </section>

        <section className="t-section-band px-6 md:px-12">
          <div className="t-content max-w-3xl">
            <h2 className="t-section-heading mb-8">{c.useHeading}</h2>
            <ol className="space-y-4 list-decimal pl-6">
              {c.useSteps.map((s) => (
                <li key={s} className="t-body">{s}</li>
              ))}
            </ol>
          </div>
        </section>

        <section className="t-section-canvas px-6 md:px-12">
          <div className="t-content max-w-2xl text-center">
            <h2 className="t-section-heading mb-4">{c.priceHeading}</h2>
            <p className="t-body">{c.priceBody}</p>
          </div>
        </section>

        <section className="t-section-band px-6 md:px-12">
          <div className="t-content max-w-2xl text-center">
            <h2 className="t-section-heading mb-5">{c.closingHeading}</h2>
            <p className="t-body-muted mb-10">{c.closingBody}</p>
            <Link href="/inspection/new" className="t-cta-primary hig-press">{c.cta}</Link>
            <p className="mt-6 text-xs text-tenu-ink-muted">{c.disclaimer}</p>
          </div>
        </section>
      </main>

      <footer className="border-t t-hairline px-6 py-10 text-center text-sm text-tenu-ink-muted">
        <p>&copy; {new Date().getFullYear()} Global Apex NET (SAS, France). tenu.world</p>
      </footer>
    </div>
  );
}
